apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-selector-excise
  labels:
    k8sType: node-selector-excise
spec:
  replicas: 2
  selector:
    matchLabels:
      PodType: node-selector-excise
  template:
    metadata:
      labels:
        PodType: node-selector-excise
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
              operator: In
              values:
              - us-east-1a
              - us-east-1b
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: topology.kubernetes.io/zone
              operator: In
              values:
              - t2.medium
      containers:
      - name: app1
        image: supergiantkir/animals:bear
        ports: 
        - containerPort: 80
        volumeMounts:
        - mountPath: /storage/app1
          name: app-storage
      - name: app2
        image: yanivomc/spring-music:latest
        ports: 
        - containerPort: 3000
        volumeMounts:
        - mountPath: /storage/app2
          name: app-storage
      volumes:
        - name: app-storage
          hostPath:
            path: /tmp/files
            type: DirectoryOrCreate
      nodeSelector:
        env: prod
