apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alpine
spec:
  template:
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        args:
        - sleep
        - "1000"
