apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear-deployment
spec:
  selector:
    matchLabels:
      app: bear
  replicas: 1
  template:
    metadata:
      labels:
        app: bear
    spec:
      containers:
      - name: bear
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moose-deployment
spec:
  selector:
    matchLabels:
      app: moose
  replicas: 1
  template:
    metadata:
      labels:
        app: moose
    spec:
      containers:
      - name: moose
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80
---
---
apiVersion: v1  
kind: Service
metadata:
  name: bear
spec:
  type: ClusterIP
  selector:
    app: bear
  ports: 
  - name: http-web 
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1  
kind: Service
metadata:
  name: moose
spec:
  type: ClusterIP
  selector:
    app: moose
  ports: 
  - name: http-web 
    protocol: TCP
    port: 80
    targetPort: 80
