apiVersion: v1
kind: ReplicaSet
metadata:
  name: spring-pod-affinity
  labels:
    app: spring-music
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-music
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      affinity:
        podAffinity:
          requiredDuringScheduleIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cache
                operator: In
                values:
                - redis
          topologyKey: kubernetes.io/os
        podAntiAffinity:
          requiredDuringScheduleIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - spring-music
          topologyKey: kubernetes.io/os
      containers:
      - name: spring-music
        image: yanivomc/spring-music:latest

apiVersion: v1
kind: Pod
metadata:
  name: redis-cache
  labels:
    cache: redis
spec:
  affinity:
    nodeAffinity:
      requiredDuringScheduleIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
            - windows
      preferredDuringScheduleIgnoredDuringExecution:
      - weight: 1
        preference:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
              - t2.medium
  containers:
  - name: redis
  image: redis:latest

          


          