apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-test-reg
spec:
  selector:
    matchLabel:
      app: nginx
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailiable: 0%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
      image: nginx:mainline-alpine
      ports:
      - containerPort: 80