apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-test
spec:
  selector:
    matchLabels:
      app: blue
  replicas: 2
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: hare
        image: supergiantkir/animals:hare
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-new
spec:
  selector:
    matchLabels:
      app: green
  replicas: 1
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: bear
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
---
apiVersion: v1  
kind: Service
metadata:
  name: my-service # Name of the service
spec:
  type: LoadBalancer
  selector:
    app: blue
    app: green
  ports: 
  - name: http-web 
    protocol: TCP
    port: 80
    targetPort: 8080
