apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: xarta
spec:
  selector:
    matchLabels:
      app: xarta
  replicas: 2
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80